---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ar68498-test-redis-pvc
  labels:
    username: ar68498
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi