---
apiVersion: v1
kind: Service
metadata:
  name: ar68498-test-flask-service
  labels:
    username: ar68498
    env: test
spec:
  type: ClusterIP
  selector:
    app: ar68498-test-flask
  ports:
  - name: ar68498-test-flask
    port: 5000
    targetPort: 5000
