---
apiVersion: v1
kind: Service
metadata:
  name: ar68498-test-redis-service
  labels:
    username: ar68498
    env: test
spec:
  type: ClusterIP
  selector:
    username: ar68498
    env: test
    app: ar68498-test-redis
  ports:
  - name: ar68498-test-redis-port
    port: 6379
    targetPort: 6379